server:
  port: 8080
spring:
  application:
    name: gateway-ai-mvc

  # 虚拟线程
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host:  ${REDIS_HOST:127.0.0.1}
      port: 6379
      password: ${REDIS_PASSWORD:}
management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{X-Request-Id}] %logger{20} - %msg%n"

gateway:
  ratelimit:
    enabled: true
    dimensions:
      ip:
        rate: 0.167
        capacity: 3
      key:
        rate: 0.5
        capacity: 10



